image: ${CI_REGISTRY}/efs/docker/ci-nodechrome:11

stages:
    - test
    - release

test:
    stage: test
    tags: ['docker', 'linux']
    script:
        - node -v
        - npm -v
        - npm i
        - npm test
        - npm run build
    coverage: '/All files\s+\|\s+(\S+)\s+\|/'

release:
    stage: release
    tags: ['docker', 'linux']
    script:
        - set -x
        - npm i
        - npm i node-jq --no-save --unsafe-perm=true
        - tmp_package=$(mktemp)
        - cat package.json | node_modules/node-jq/bin/jq ".name = \"$CI_PROJECT_NAME\"" > $tmp_package
        - cat $tmp_package > package.json
        - npm run build
        - npm config set registry "http://nexus.ert.com/nexus/content/repositories/npm-automation"
        - npx semantic-release
    only:
        refs:
            - master
            - beta
