image: ${CI_REGISTRY}/efs/docker/ci-nodechrome:11
variables:
    PACKAGE_NAME: ert-ngx-modal2

stages:
    - test
    - release

test:
    stage: test
    tags: ['docker', 'linux']
    script:
        - node -v
        - npm -v
        - npm i
        - npm test
        - npm run build
    coverage: '/All files\s+\|\s+(\S+)\s+\|/'

release:
    stage: release
    tags: ['docker', 'linux']
    script:
        - npm i
        - npm i -g node-jq
        - cat package.json | jq ".name = \"$PACKAGE_NAME\"" > package.json
        - npm run build
        - npm config set registry "http://nexus.ert.com/nexus/content/repositories/npm-automation"
        - npx semantic-release
    only:
        refs:
            - master
            - beta
