image: ${CI_REGISTRY}/efs/docker/ci-nodechrome:10

stages:
    - test
    - release

test:
    stage: test
    tags: ['docker', 'linux']
    script:
        - node -v
        - npm -v
        - npm i
        - npm test
        - npm run build
    artifacts:
        paths:
            - dist
        expire_in: 1h

release:
    variables:
        GIT_STRATEGY: none
    stage: release
    tags: ['docker', 'linux']
    script:
        - npm i
        - npx semantic-release
    only:
        refs:
            - master
