#!/bin/bash
PATH="$PWD/node_modules/.bin":$PATH

dev2() {
    npm run eslint:w 2>&1 &
    npm run test:w 2>&1 &
}

build() {
    ng-packagr
    mv src/*.metadata.json dist
    cp src/ngx-modal.css dist
}

"$@"
