#!/bin/bash
PATH="$PWD/node_modules/.bin":$PATH

dev2() {
    npm run eslint:w 2>&1 &
    npm run test:w 2>&1 &
}

build() {
    ng-packagr
    mv src/ngx-modal2.metadata.json dist
    cp src/ngx-modal.css dist
}

eslint_run() {
    eslint src --ext ts
}

# eslint_watch() {
#     eslint_run
#     inotifywait_cmd=`watch_cmd`
#     while true; do
#         $inotifywait_cmd -r src && \
#             eslint_run
#     done
# }

watch_cmd() {
    case `uname -o` in
        Linux)
            echo 'inotifywait'
        ;;
        Msys)
            echo 'inotifywait-win32.cmd'
        ;;
        *)
            echo 'inotifywait'
        ;;
    esac
}

"$@"
